- name: Install Containerd as container runtime on clients
  hosts: clients
  vars_files:
    - vault.yml
  tasks:
    - name: Check Ip route exists
      command: 'ip route show default'
      register: ip_route

    - name: set Gateway IP
      become: yes
      command: 'sudo ip route add default via {{ gateway_ip }}'
      when: '"default via" not in ip_route.stdout'

    - name: run command to set GateWay IP from vars
      become: yes
      command: 'sudo ip route change default via {{ gateway_ip }}'
      when: '"default via" in ip_route.stdout'

    - name: Check DNS server
      command: 'cat /etc/resolv.conf'
      register: dns_server

    - name: set DNS server
      become: yes
      command: 'echo -e "\nnameserver 178.22.122.100\nnameserver 185.51.200.2" | sudo tee -a /etc/resolv.conf'
      when: '"nameserver" not in dns_server.stdout'

    - name: Change repositories to use local mirror
      become: yes
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644

    - name: Update package
      become: yes

      apt:
        update_cache: yes
        cache_valid_time: 3600

    # - name: Download Containerd
    #   get_url:
    #     url: https://github.com/containerd/containerd/releases/download/v1.7.22/containerd-1.7.22-linux-amd64.tar.gz
    #     dest: /tmp/containerd-1.7.22-linux-amd64.tar.gz

    # - name: Extract Containerd
    #   command: 'tar -xvf /tmp/containerd-1.7.22-linux-amd64.tar.gz -C /tmp/containerd-1.7.22'

    # - name: Add Containerd service
    #   become: yes
    #   command: 'sudo cp /tmp/containerd-1.7.22/bin/* /usr/bin/'

    - name: Install Containerd
      become: yes
      apt:
        name: containerd
        state: present

    - name: enable and start containerd
      become: yes
      service:
        name: containerd
        enabled: yes
        state: started

    - name: Check directory exists
      command: 'ls /etc/containerd'
      register: containerd_dir

    - name: create configuration directory
      become: yes
      command: 'sudo mkdir -p /etc/containerd'
      when: containerd_dir.stdout == ''

    - name: Configure containerd
      become: yes
      command: 'sudo containerd config default | sudo tee /etc/containerd/config.toml'

    - name: Restart containerd
      become: yes
      service:
        name: containerd
        state: restarted

    - name: Install some requirements
      become: yes
      apt:
        name: apt-transport-https, ca-certificates, curl, gnupg, lsb-release
        state: present

    - name: check if kubernetes repository key exists
      command: 'ls /etc/apt/keyrings/'
      register: kubernetes_keyls 

    - name: Add Kubernetes repository key
      become: yes
      command: 'curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'
      when: '"kubernetes-apt-keyring.gpg" not in kubernetes_keyls.stdout'

    - name: Add Kubernetes repository
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /'
        create: yes
        state: present

    - name: Update package
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Kubernetes
      become: yes
      apt:
        name: kubelet, kubeadm, kubectl
        state: present

    - name: pin Kubernetes version
      become: yes
      command: 'sudo apt-mark hold kubelet kubeadm kubectl'

    - name: enable and start kubelet
      become: yes
      service:
        name: kubelet
        enabled: yes
        state: started




    
    



    
